Traceback (most recent call last):
  File "C:\Users\mirjam\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\mirjam\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
tree = ET.parse('ddd_010097934_mpeg21_a0001_ocr.xml')
root_article = tree.getroot()
print(ET.tostring(root_article, encoding='utf8').decode('utf8'))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [1;32mIn [9][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m tree [38;5;241m=[39m [43mET[49m[38;5;241;43m.[39;49m[43mparse[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mddd_010097934_mpeg21_a0001_ocr.xml[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      2[0m root_article [38;5;241m=[39m tree[38;5;241m.[39mgetroot()
[0;32m      3[0m [38;5;28mprint[39m(ET[38;5;241m.[39mtostring(root_article, encoding[38;5;241m=[39m[38;5;124m'[39m[38;5;124mutf8[39m[38;5;124m'[39m)[38;5;241m.[39mdecode([38;5;124m'[39m[38;5;124mutf8[39m[38;5;124m'[39m))

File [1;32m~\anaconda3\lib\xml\etree\ElementTree.py:1229[0m, in [0;36mparse[1;34m(source, parser)[0m
[0;32m   1220[0m [38;5;124;03m"""Parse XML document into element tree.[39;00m
[0;32m   1221[0m 
[0;32m   1222[0m [38;5;124;03m*source* is a filename or file object containing XML data,[39;00m
[1;32m   (...)[0m
[0;32m   1226[0m 
[0;32m   1227[0m [38;5;124;03m"""[39;00m
[0;32m   1228[0m tree [38;5;241m=[39m ElementTree()
[1;32m-> 1229[0m [43mtree[49m[38;5;241;43m.[39;49m[43mparse[49m[43m([49m[43msource[49m[43m,[49m[43m [49m[43mparser[49m[43m)[49m
[0;32m   1230[0m [38;5;28;01mreturn[39;00m tree

File [1;32m~\anaconda3\lib\xml\etree\ElementTree.py:569[0m, in [0;36mElementTree.parse[1;34m(self, source, parser)[0m
[0;32m    567[0m close_source [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[0;32m    568[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mhasattr[39m(source, [38;5;124m"[39m[38;5;124mread[39m[38;5;124m"[39m):
[1;32m--> 569[0m     source [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43msource[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m    570[0m     close_source [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m    571[0m [38;5;28;01mtry[39;00m:

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'ddd_010097934_mpeg21_a0001_ocr.xml'
FileNotFoundError: [Errno 2] No such file or directory: 'ddd_010097934_mpeg21_a0001_ocr.xml'

