Traceback (most recent call last):
  File "C:\Users\mirjam\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\mirjam\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
chapter_list = []
c_counter = 1
p_counter = 1 

for div in root.find_all('div'):
	if div.get('type') == 'chapter':
		chapter = "chapter_" + str(c_counter)
		content = div.text
		for poems in div.find_all('lg'):
			if poems.get('type') == 'poem':
				poem = "poem_" + str(p_couter)
				p_content = poems.text
				chapter_list.append([chapter, poem, p_content])
				p_counter += 1
		c_counter += 1
		p_counter = 1

poems  = pd.DataFrame(chapter_list, columns = ['chapter', 'poem', 'content'])
poems
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [6][0m, in [0;36m<cell line: 6>[1;34m()[0m
[0;32m     10[0m [38;5;28;01mfor[39;00m poems [38;5;129;01min[39;00m div[38;5;241m.[39mfind_all([38;5;124m'[39m[38;5;124mlg[39m[38;5;124m'[39m):
[0;32m     11[0m 	[38;5;28;01mif[39;00m poems[38;5;241m.[39mget([38;5;124m'[39m[38;5;124mtype[39m[38;5;124m'[39m) [38;5;241m==[39m [38;5;124m'[39m[38;5;124mpoem[39m[38;5;124m'[39m:
[1;32m---> 12[0m 		poem [38;5;241m=[39m [38;5;124m"[39m[38;5;124mpoem_[39m[38;5;124m"[39m [38;5;241m+[39m [38;5;28mstr[39m([43mp_couter[49m)
[0;32m     13[0m 		p_content [38;5;241m=[39m poems[38;5;241m.[39mtext
[0;32m     14[0m 		chapter_list[38;5;241m.[39mappend([chapter, poem, p_content])

[1;31mNameError[0m: name 'p_couter' is not defined
NameError: name 'p_couter' is not defined

